#!/usr/bin/env bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

TMPDIR=/tmp

# The first argument is a path to the directory containing the build's full set of sources.
source_dir=$1
cd $source_dir

payload=$(mktemp $TMPDIR/knife-resource-request.XXXXXX)
cat > $payload <&0

# Required.
knife_command="$(jq -r '.params.knife // ""' < $payload)"
if [[ -z "$knife_command" ]]; then
  echoerr 'knife must be specified in params.'
  exit 1
fi

certificate="$(jq -r '.params.certificate // ""' < $payload)"
if [[ -z "$certificate" ]]; then
  echoerr 'certificate must be specified in params.'
  exit 1
fi

chef_url="$(jq -r '.params.chef_url // ""' < $payload)"
if [[ -z "$chef_url" ]]; then
  echoerr 'chef_url must be specified in params.'
  exit 1
fi

echo $certificate > ~/.chef/concourse.pem
sed -i "s/CHEF_SERVER_URL/$chef_url/" ~/.chef/credentials
exec knife $(eval "echo $knife_command") >&3
